### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by hroptatyr** [charles-cooper/itch-order-book#1]
What is the suggested compiler for this?  I tried:

    $ clang++ --version
    clang version 3.3 (branches/release_33 183898)
    $ g++ --version
    g++ (SUSE Linux) 4.8.1 20130909 [gcc-4_8-branch revision 202388]
    $ icpc --version
    icpc (ICC) 17.0.4 20170411

and none of them works.

    g++ -O3 -march=native -std=c++1y main.cpp bufferedreader.cpp
    In file included from main.cpp:6:0:
    itch.h:28:46: error: template declaration of 'constexpr const unsigned char netlen'
     template<MSG __type> unsigned char constexpr netlen = -1;

**Comment by charles-cooper** [comment]
Hi @hroptatyr !
A little bit more information about your system might be helpful to further diagnose the issue. The included build script works with the following versions of `clang` and `gcc`:
```
$ clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Based on my quick googling, the versions you listed have incomplete implementations of C++14 (aka C++1y) - this codebase depends on a feature-complete implementation of C++14.

Let me know if upgrading helps!
