### ISSUE TITLE
During replace ask is converted to bid bug?

### ISSUE THREAD

**Issue by skuch89** [charles-cooper/itch-order-book#12]
Hi @charles-cooper,

Thank you for really interesting approach of building order book. Recently I have been investigating various implementations available as an open-source and your implementation I find at this moment is one of most comprehensive ones, though code base isn't that big! :)
Anyways, I've got a query. During replace, specifically for this part of code:
https://github.com/charles-cooper/itch-order-book/blob/095ac97ef46c72411a62dd9148d96d2e3ace3305/order_book.h#L328

Why ask price (negative) is converted for bid price (positive) during replace?

As an example (using BOOST unit testing):
```
BOOST_AUTO_TEST_CASE(TestForCharlesCooper)
{
    // add ask orders
    order_book::add_order(order_id_t(1), book_id_t(1), sprice_t(-2500), qty_t(25));
    order_book::add_order(order_id_t(2), book_id_t(1) ,sprice_t(-2350), qty_t(5));

    // Expect 2 ask orders & 0 bids
    BOOST_CHECK(order_book::s_books[1].m_offers.size() == 2);
    BOOST_CHECK(order_book::s_books[1].m_bids.size() == 0);

    // Now replace best ask to lower it
    order_book::replace_order(order_id_t(2), order_id_t(3), qty_t(5), sprice_t(-2400));

    // Expect 2 ask orders
    BOOST_CHECK(order_book::s_books[1].m_offers.size() == 2);
    BOOST_CHECK(order_book::s_books[1].m_bids.size() == 0);
}
```

using gdb I see following:

```
(gdb) p order_book::s_books[1].m_bids
$10 = std::vector of length 1, capacity 1 = {{
    m_price = (unknown: 0x960),
    m_ptr = (unknown: 0x1)
  }}
(gdb) p order_book::s_books[1].m_offers
$11 = std::vector of length 1, capacity 2 = {{
    m_price = (unknown: 0xfffff63c),
    m_ptr = 0
  }}
(gdb) p (int)order_book::s_books[1].m_bids.begin()->m_price
$12 = 2400
(gdb) p (int)order_book::s_books[1].m_offers.begin()->m_price
$13 = -2500
(gdb)
```
I think following code is redundant:
```
  static void replace_order(order_id_t const old_oid, order_id_t const new_oid,
                            qty_t const new_qty, sprice_t new_price)
  {
#if TRACE
    printf("REPLACE %lu %lu %d %u\n", old_oid, new_oid, new_price, new_qty);
#endif  // TRACE
    order_t *order = oid_map.get(old_oid);
    order_book *book = &s_books[MKPRIMITIVE(order->book_idx)];
    bool const bid = is_bid(book->s_levels[order->level_idx].m_price);
    book->DELETE_ORDER(order);
    //TODO Bug?
    /*if (!bid) {
      new_price = sprice_t(-1 * MKPRIMITIVE(new_price));
    }*/
    book->add_order(new_oid, order->book_idx, new_price, new_qty);
  }
};
```

**Comment by charles-cooper** [comment]
dup of https://github.com/charles-cooper/itch-order-book/issues/7, please reopen if you still have some more questions!

**Comment by skuch89** [comment]
Hi @charles-cooper,

Thank you for your reply,
I'm not sure I am following your response at this moment. Why would replace ask order is converted to bid?
In reference to https://github.com/charles-cooper/itch-order-book/issues/7 the conversation is about performance, but would replacing ask to bid be expected?  (question not relates to performance, but rather correctness)
As per example shown above, ask order is '2350' (negative, as asks are represented negative, so -2350), and when replaced to another ask '2400' (negative would be -2400), it converts to bid, not ask.
I would have expected ask replace order should convert to both bid/ask as requested, but code suggests it is always converted to bid:
```
if (!bid) {
      new_price = sprice_t(-1 * MKPRIMITIVE(new_price));
    }
```
e.g.
[ask replace]: -2400 is !bid and therefore -> sprice_t(-1 * -2400) -> bid 2400.
[bid replace]: 2400 is bid, and therefore isn't going inside if statement & stays bid 2400
Am I making mistake somewhere above?

**Comment by charles-cooper** [comment]
if you look at how replace_order is called, it is always called with a positive number for the price.
https://github.com/charles-cooper/itch-order-book/blob/095ac97ef46c72411a62dd9148d96d2e3ace3305/main.cpp#L141-L146

i apparently left a comment that there is a code smell since the logic is a bit weird :) but even so, i think it is correct.

**Comment by skuch89** [comment]
Thank you for reponse @charles-cooper,
Indeed, didn't notice that bit. If it is only for bids I suppose it is ok (guess it is checking overflow, but would need to perform some recalcs to re-confirm) 👍 
Otherwise, would ask order replace then not implemented? From NASDAQ documentation looks like ask replace should be supported as well: https://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/NQTVITCHSpecification.pdf (page 15).

Thanks,

**Comment by charles-cooper** [comment]
> Otherwise, would ask order replace then not implemented? From NASDAQ documentation looks like ask replace should be supported as well: https://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/NQTVITCHSpecification.pdf (page 15).

that's not really what's happening. the bid/ask is not specified in the message, since that cannot be updated in the replace order message. instead, it is expected that you look up the bid/ask nature of the order internally (given the order id), that's what this line does:
https://github.com/charles-cooper/itch-order-book/blob/095ac97ef46c72411a62dd9148d96d2e3ace3305/order_book.h#L326

so replace_order always passes in a positive number for the price (the positive sign can therefore be thought of as a dummy value) and then the sign is applied after the internal lookup.

**Comment by gzaharovs** [comment]
Yep, I have tested now. I see, my mistake was that I was converting to the negative price before sending to the replace_order method. It was not clear (at least for me :)) that a positive should have been sent. So this step works fine now:
```

    // MISTAKE found!
    //order_book::replace_order(order_id_t(2), order_id_t(3), qty_t(5), sprice_t(-2400));
    order_book::replace_order(order_id_t(2), order_id_t(3), qty_t(5), sprice_t(2400));

    // PASS NOW!
    // Expect 2 ask orders
    BOOST_CHECK(order_book::s_books[1].m_offers.size() == 2);
    BOOST_CHECK(order_book::s_books[1].m_bids.size() == 0); 
```

Thank you @charles-cooper for help)) Now all makes sense. Really good job 👍

**Comment by skuch89** [comment]
Yep, I see now. My mistake was that I've sent a negative s_price in assumption that it should always be used for asks, though during order_replace it is expected to be positive (signed)
```
    // Now replace best ask to lower it
    // MISTAKE
    // order_book::replace_order(order_id_t(2), order_id_t(3), qty_t(5), sprice_t(-2400));
    order_book::replace_order(order_id_t(2), order_id_t(3), qty_t(5), sprice_t(2400));

    // ALL works now!
    // Expect 2 ask orders
    BOOST_CHECK(order_book::s_books[1].m_offers.size() == 2);
    BOOST_CHECK(order_book::s_books[1].m_bids.size() == 0);
```
Thank you a lot for your time @charles-cooper , appreciate 👍 It is really good job you've done!
