### ISSUE TITLE
Missing file ?

### ISSUE THREAD

**Issue by ttuanho** [charles-cooper/itch-order-book#5]
I cannot run build since the `itch.h` includes the `endian.h` which does not exist:

```
$ sh build.sh 
In file included from main.cpp:6:
./itch.h:2:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from main.cpp:6:
./itch.h:2:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
```
 I'm on MacOs Mojave 10.14.4. 
```
$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I have googled the issue but [this](https://stackoverflow.com/questions/27073837/fatal-error-endian-h-file-not-found) does not help.

Thanks.

**Comment by charles-cooper** [comment]
Hey @ttuanho sorry for the slow response. Can you check out #6 and see if that fixes your issue. Thanks

**Comment by ttuanho** [comment]
No but thanks for the help. My machine doesn't have the file either but I found out we can re-defined the functions from [this issue](https://gist.github.com/yinyin/2027912) and just simply added to your [types.h](/types.h) or `/usr/local/include` if wanna modify the environment. It works now!

Impressive work on this btw.
